create table public.todos (
  id uuid not null default gen_random_uuid (),
  counter bigint generated by default as identity not null,
  text text null,
  done boolean null default false,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  deleted boolean null default false,
  constraint todos_pkey primary key (id)
) TABLESPACE pg_default;

create trigger set_updated_at BEFORE
update on todos for EACH row
execute FUNCTION update_updated_at_column ();

create publication supabase_realtime for table todos;